import Head from "next/head"
import { Raleway } from "@next/font/google"
import HeadBar from "@/Components/HeadBar";
import styles from "@/styles/Home.module.css"
import Tabs from "@/Components/Tabs";
import {useState} from "react";
import ProductListContainer from "@/Components/ProductListContainer";

const raleWay = Raleway({ subsets: ["latin"] })

export default function Home() {
  const [productList, setProductList] = useState([]);

  const handleProducts = (products) => {
    setProductList(products?.payload?.products);
  }

  return (
    <>
      <Head>
        <title>Matspar App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={raleWay.className}>
        <HeadBar setProducts={handleProducts} productList={productList}/>
        <h3 className={styles.homeTitle}>Find your favorite products now.</h3>
        <Tabs />
        <ProductListContainer productList={productList} />
      </main>
    </>
  )
}
