import Head from 'next/head'
import Image from 'next/image'
import { Raleway } from '@next/font/google'
import HeadBar from "@/Components/HeadBar";
import styles from '@/styles/Home.module.css'
import Tabs from "@/Components/Tabs";
import ProductCard from "@/Components/ProductCard";

const raleWay = Raleway({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={raleWay.className}>
        <HeadBar />
        <content>
          <h3 className={styles.homeTitle}>Find your favorite products now.</h3>
          <Tabs />
          <ProductCard />
        </content>
      </main>
    </>
  )
}
